;;; gptel-commit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gptel-commit.el

(autoload 'gptel-commit "gptel-commit" "\
Generate commit message with configured backend (GPTel or Claude Code)." t)
(autoload 'gptel-commit-rationale "gptel-commit" "\
Prompt user for rationale and generate commit message with configured backend." t)
(register-definition-prefixes "gptel-commit" '("gptel-commit-"))

;;; End of scraped data

(provide 'gptel-commit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gptel-commit-autoloads.el ends here
