;;; gptel-magit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gptel-magit.el

(autoload 'gptel-magit-install "gptel-magit" "\
Install gptel-magit functionality.")
(register-definition-prefixes "gptel-magit" '("gptel-magit-"))

;;; End of scraped data

(provide 'gptel-magit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gptel-magit-autoloads.el ends here
